### PR TITLE
Feature/show accept terms

### PR DESCRIPTION
**Pull request by joshbax189**
~Blocked by MEE-1294: vault doesn't save share terms.~ Working against vault-dev, stage and sandbox still return null for share terms.

Follow up to #113 (includes it, so merge this one instead)

Changes 
- `meeco shares:create -c share.config.yaml --accept "My Terms Go Here"`
- `meeco shares:accept share_id` will display "My Terms Go Here" and prompt for confirmation

**Question: should --accept just be an entry in the config file?**

### CODE REVIEW

**Review by zbarbuto — COMMENTED** [review]
`--accept` on `shares:create` feels like a bit of a misnomer to me - what you're defining is `terms`.

Also, what are your thoughts on just adding a `-y` flag to `shares:accept` as well to auto-accept? Just for the poor windows users who don't have the `yes` program 😁

**Comment by zbarbuto** [comment]
I get the reasoning since the property is `acceptTerms` it's just `shares:create -c .shareConfig.yaml --terms "Please no steal my data"` feels a bit more idiomatic.

**Comment by joshbax189** [comment]
I like the auto accept idea.

I was also wondering about `--accept` it's probably an artefact of doing the change in two PRs. And how often will terms be a one line thing? If it's anything like a standard T&Cs text, it's a wall. Probably best to just have it as a field in the config/scaffold yaml. (In fact terms and expiry are the ONLY useful stuff in the scaffold, and no other `X:create` commands have flags like that).

It would be different if you could actually just do sth like `meeco shares:create -c connection [item yaml|item id]` and skip the scaffold entirely.

The one downside is that you would need some fiddling to do `e2e-accept-share` say.

**Comment by zbarbuto** [comment]
Yeah was wondering that myself about the wall of text. Perhaps as an alternative the options should be:

1. As part of the share config.yaml
2. As a separate text file

And remove the option for it as a CLI string completely.

**Comment by joshbax189** [comment]
The text file input is a nice idea! In that case I'll roll expiry into the config.yaml too so it matches every other X:create command.

**Comment by joshbax189** [comment]
Actually, this raises a whole lot of questions related to the yaml standardisation ticket Jan mentioned. Better to do that all together. I'll leave the flags where they are until a later PR.

**Review by vijayshiyani — APPROVED** [review]

**Pull request merged**
