### PR TITLE
Feature/display page

### PR DESCRIPTION
**Pull request by izzypesk**
@zbarbuto I have set up a demo page in the style-kit folder (similar to the one you created in the sdk folder)

- The purpose is to show the components in the context they were intended
- To test out the components amongst other components
- To view it just run  **npm run start-demo**
- I will update the style-kit docs to include this
Screen Shot 2020-07-16 at 5 13 19 pm

### CODE REVIEW

**Comment by zbarbuto** [comment]
There are a few sizing issues on smaller screens.

Also what are your thoughts as including this as another page in the storybook rather than its own app - that way it will be more easily published to the github.io page

image

**Comment by izzypesk** [comment]
Yeah, I noticed that late last night - on my to-do list today.

And sure thing about making it a page in storybook - do I make it its own tab like each component has and just called it demo page?

**Comment by zbarbuto** [comment]
Yeah call it demo page or kitchen sink

**Comment by izzypesk** [comment]
I have moved that across to storybook now and removed the demo folder in the style kit

**Pull request merged**
