### PR TITLE
Run pre-test version checks and automatically tag alpha/beta versions

### PR DESCRIPTION
**Pull request by zbarbuto**
This PR is an RFC to help address some ongoing mistakes commonly made in the repo. I'll leave this open for discussion for a bit as it might create some frustration in updating packages but overall I think it will encourage better practices.

This deprecates committing "-beta" versions to the repo.

The general idea is that the new "pretest" script (which is run automatically by npm when you run `npm test`) will check for following mistakes:

1. That your package name matches the name in the `packages` folder:  
image

2. That you use valid semver versions (no `-beta` tags etc.):  
image

3. That all inter-dependant packages can be satisfied from inside the repo. That is, if you are bumping the version of a package you have updated all other packages that depend on it to work with your changes:  
image

4. That all packages depend on semver compatible versions of "vault-api-sdk" and "keystore-api-sdk":  
image

As for publishing "beta" versions - there is another new script "tag-packages" which accepts an extra argument of "beta" or "alpha". This script will do the following:

- For *all* packages: add the `-beta` (or `-alpha`) pre-release tag to the current version
- Update all interdependent packages to just list `"beta"` (or `"alpha"`) as the required version (which npm knows how to resolve)

This script is run automatically in all the beta/alpha release workflows. The idea being that the packages are tagged before publish (so we never commit "beta" versions to the repo) and that we don't have to juggle "x.y.z-beta" versions of packages before publishing.

So essentially when making a change you just bump the semver version of the package you touch as applicable and the pretest script will yell at you with what to do from that point on.

### CODE REVIEW

**Comment by joshbax189** [comment]
Through cleverness I have figured that npm package.json version strings and release tags are completely independent:
- sdk `x.y.z-beta.1` released as a major release
- fs-common `4.0.0` released as a beta
Seems like this script would fix those problems!

**Comment by zbarbuto** [comment]
Yes - although I couldn't find an example if a version that wasn't string-tagged being npm tagged - and I'm not sure that if you had "4.0.0" in your package-json that it would resolve to a non-"latest" version - so I think the tagging script is still worth keeping in there (unless I'm wrong...)

**Comment by joshbax189** [comment]
> I'm not sure that if you had "4.0.0" in your package-json that it would resolve to a non-"latest" version
For interest: we had fs-common 4.0.0 tagged as beta, 3.1.1 as latest...
- `"file-storage-common": "^4.0.0"` installs 4.0.0 ignoring tags
-  `"file-storage-common": ">=3.0.0"` installs 3.1.1
The thing that would prevent us using only npm tags (and no semver tags) is that release versions would need a higher version number, and you couldn't tell which historical versions were betas or stable releases.

**Comment by zbarbuto** [comment]
> "file-storage-common": "^4.0.0" installs 4.0.0 ignoring tags
> "file-storage-common": ">=3.0.0" installs 3.1.1

Ah I understand. So the `-tag` pre-release tag at the end prevents installing `4.0.0` unless you actually manually opt-in by adding that tag since:

"file-storage-common": "^4.0.0-beta" wouldn't resolve to 4.x.x without the tag but "file-storage-common": "^4.0.0" does.

and since

`npm install file-storage-common@latest` will give you 3.1.1
`npm install file-storage-common` will default to `latest` (3.1.1)
`npm install file-storage-common@beta` will give you the 4.0.0

If that's the case I think I like the idea of including the tag in the version name as well just for that extra bit of clarity maybe? I realise you can add and remove tags after the fact but CI would need to be a bit more complex as it would need to check if the version is published first, add `@latest` if it is or `publish @latest` if it isn't.

**Pull request merged**
