### PR TITLE
Change/client task queue api

### PR DESCRIPTION
**Pull request by vijayshiyani**

### CODE REVIEW

**Comment by joshbax189** [comment]
Overlaps some client task changes in #124, which was waiting for a release. If you want, I can make a version that does not have breaking API changes, and merge it with this, that way you can have your pie and eat it too.

**Review by zbarbuto — APPROVED** [review]

**Comment by vijayshiyani** [comment]
> Overlaps some client task changes in #124, which was waiting for a release. If you want, I can make a version that does not have breaking API changes, and merge it with this, that way you can have your pie and eat it too. (I'll do it tomorrow)

I am ok with that, let's do it.

**Comment by joshbax189** [comment]
vijays changes in client-task-queue-service
- change list() to accept an array of states, invert meaning of suppressStateChange (deployed in dev env only) sim. for listAll
- use client state enum in CLI and match flag meanings

my changes on top of that:
- export ClientTaskQueueGetStateEnum as ClientTaskState
- add IClientTaskExecResult
- rename executeClientTask to execute
- execute() sets tasks to in_progress before attempting them
- updateSharesClientTask re-uses ShareService.updateSharedItem
- add CLI command client-task-queue:update to manually set task state
- state filter args which are not valid are ignored, no error is thrown

**Comment by joshbax189** [comment]
the variables env.SANDBOX_VAULT_URL etc were printing out as 'null', so I manually set them to vault-dev.meeco.me in the jenkinsfile

**Comment by joshbax189** [comment]
Note: first merge develop into master, then merge this branch into develop, taking the new copies (our) of package files and jenkins file

**Pull request merged**
