### PR TITLE
Feature/node upgrade

### PR DESCRIPTION
**Pull request by ragnika**
by no definition, is complete.

@linasi @vijayshiyani @Matthew-Meeco 

but it looks like `nock(<URL>, api => { // set mock via api.get(), etc }` does not seem to work anymore

calling it in a  `before(function() {})` block worked.

So, there might be a need to have a look through the failing tests and updating them.

 Organization-services login
    ✔ returns organization service agent login information

### CODE REVIEW

**Comment by ragnika** [comment]
experimented further, for some reason, nock needs to be explicitly imported and the mocked `url` needs to called in a `before` block.

managed to pass the test locally

Screenshot 2024-08-09 at 5 37 10 PM

**Comment by linasi** [comment]
Hi @ragnika @Matthew-Meeco, seems that the problem was linked to multiple versions of `nock` library being installed.
As you can see, `nock` is not a direct dependency. It comes via `@oclif/test` -> `fancy-test` -> `nock`. I assume at some point `nock` was added as a direct dependency to the package to use the latest version.
Once `nock` v4 was released `npm`, direct dependency was upgraded but the one that comes via `@oclif/test` was not.
`@oclif/test` used in this project is very outdated. I have added overrides to make same `nock` version is installed everywhere for now.

**Comment by ragnika** [comment]
@linasi this looks good to me, do we want to merge this in?

~I'm assuming `node-fetch` stays as a dependency?~

I can use `configureFetch` as we discussed elsewhere.

**Comment by linasi** [comment]
Yes. I am going to do that.

**Review by linasi — APPROVED** [review]
👍

**Pull request merged**
