### PR TITLE
Task/updating vc api sdk

### PR DESCRIPTION
**Pull request by vijayshiyani**
vc API SDK update to version 10+

### CODE REVIEW

**Comment by linasi** [comment]
@vijayshiyani why don't we wait until all API changes are ready to be integrated?

**Comment by vijayshiyani** [comment]
> @vijayshiyani why don't we wait until all API changes are ready to be integrated?

Initially, I thought OCW would need to use this since it's utilizing the SDK, but then I realized it has a package override for the vc-api-sdk. We can release this now, that will allow portal work to start.

//cc @linasi

**Comment by linasi** [comment]
Unless somebody asks for this or it blocks something, I would wait until all API changes are in place.

**Review by linasi — APPROVED** [review]
👍

**Comment by leikind** [comment]
@CodiumAI-Agent /improve

**Pull request merged**
