### PR TITLE
Remove thumbnail and attachment from meeco/sdk

### PR DESCRIPTION
**Pull request by zbarbuto**
*Breaking Change*

This PR removes thumbnail and attachment related methods from `ItemService` (and their respective tests) and temporarily disables the `get-thumbnail` CLI command.

This is a breaking change so both CLI and SDK should have a major version bump after this is merged.

- Remove methods for attaching and getting file from meeco/sdk (file-stroage package should be used instead)
- Attaching thumbnails will be added to the file-storage package in the near future
- The jimp package was massively bloating the size of the sdk bundle
- Makes get-thumbnail command throw a command disabled error
- Once thumbnail support is added to file-storage, the get-thumbnail command can be re-enabled

### CODE REVIEW

**Review by vijayshiyani — APPROVED** [review]
LGTM

**Comment by joshbax189** [comment]
Just double checking: you just wanted to disable items:get-thumbnail, not items:get-attachment as it says in the comment?

**Comment by zbarbuto** [comment]
> Just double checking: you just wanted to disable items:get-thumbnail, not items:get-attachment as it says in the comment?

Correct - have fixed the OP. `get-attachment` already uses the `file-storage-node` package as it should.

**Comment by joshbax189** [comment]
Nice. LGTM otherwise. My PRs #113 and #114 have breaking changes to the CLI too, shall we bundle them into the same version release?

**Review by joshbax189 — APPROVED** [review]

**Review by spazworm — APPROVED** [review]

**Pull request merged**
